### ISSUE TITLE
Combine category and event type

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#101]
Currently, we have two separate fields for category and event type.

In a default JSON form, you'd have:
```
{
    category: "transport",
    type: "parameters_set"
}
```

However, the event type names (e.g., `parameters_set`, `state_updated`) aren't unique to the categories at the moment. 

This can lead to some issues:
- Processing qlog requires you to always check the category as well (cannot just look at the event_type)
- Makes them difficult to encode in formats like protobuf (e.g., https://github.com/quiclog/pcap2qlog/blob/binary/src/converters/types/qlog.proto#L54) (and I assume things like serde as well @LPardue?) because you cannot easily de-serialize based just on the type-name.

One solution would be to combine both into one field:
```
{
    type: "transport:parameters_set"
}
```

This should make it easier to de-serialize just based on the type field (and make it into an enum) and easier to do a `switch` when processing events. 

Another option would be to make sure each event has a unique name, but that would come down the pre-pending the category (or something similar) anyway afaict (e.g., `transport_parameters_set`), which is basically the same thing. 

I don't see many use cases where you'd only want to log one category (and thus could leave that out and just log the event names to save some space). I also don't know if compression would be that much worse overall if we'd combine the two into one field. If we'd move to regular JSON as the default (#89), it would probably save space, as then we'd only have a single field per-object instead of 2 (as in the examples above).

What do people think? CC @LPardue  @marten-seemann @mpiraux @triplewy @mikkelfj @nibanks @jlaine

**Comment by marten-seemann** [comment]
Makes sense to me. I support making this change.
