### ISSUE TITLE
remove redundant length fields

### ISSUE THREAD

**Issue by marten-seemann** [quiclog/internet-drafts#102]
Once we require hex-encoding for byte-fields (which, as far as I can see from other peoples' qlogs, is already the de-facto standard), we don't need length fields any more. This applies to the `scil` and `dcil` in the `Header` (as well as the proposed token length in #94), the `NewTokenFrame`, `NewConnectionIDFrame` (and probably also the QPACK events, but I'm not an expert on those).

**Comment by rmarx** [comment]
I kind of disagree, as I think an important use case is where you'd not want to log the raw values but only the lengths. 

We can argue whether that's the case for the CIDs of course, but for tokens and qpack data (and, obviously, payloads), I think people should have the option to not log the raw values. 

This flows from privacy/security concerns, as well as storage efficiency for larger deployments. 

I do think we could add text stating something like "if you log the raw values in hex, the length field is redundant, and tools SHOULD be able to derive length from hex"?

**Comment by marten-seemann** [comment]
Good point. I can see why you want to log tokens (since they create a correlation spanning two separate connections).

> I do think we could add text stating something like "if you log the raw values in hex, the length field is redundant, and tools SHOULD be able to derive length from hex"?

I'd make this an even stronger statement: ""if you log the raw values in hex, the length field is redundant and SHOULD be omitted. Tools MUST be able to derive length from hex".

**Comment by rmarx** [comment]
Fixed by above commits.

Main draft now explains how truncated raw byte values should be accompanied by a length field and that tools should be able to derive the length field from the raw byte values. 

Event definitions draft references this explicitly when discussing the RawInfo approach.
