### ISSUE TITLE
push_allowed may be misleading

### ISSUE THREAD

**Issue by dtikhonov** [quiclog/internet-drafts#110]
The "push_allowed" data element is `parameters_set` event is odd in that other data elements log actual settings values while "push_allowed" is derived from the value of `MAX_PUSH_ID` frame.

In addition, for pushing to be allowed, a second condition is necessary:  There must be enough unidirectional stream credit.  For example, if only three unidirectional streams are allowed, it effectively means that pushing is not possible, as those will be taken by the control and the two QPACK streams.

**Comment by rmarx** [comment]
I agree this is unclear.
The thinking was that you'd be able to see the MAX_PUSH_ID frame when that's logged as part of `frame_created` or `frame_parsed` and the `push_allowed` would be a more high-level indicator if applications don't log the frames individually (e.g., to save space).

Given this, would you advocate:
1. removing `push_allowed` altogether
2. properly defining `push_allowed` as meaning both MAX_PUSH_ID > 0 AND unidirectional credit at the same time
3. replacing `push_allowed` with a `max_push_id` field

**Comment by dtikhonov** [comment]
Well, `MAX_PUSH_ID` is already logged, so we don't need (3).  (2) may be onerous to log because now the implementation needs to add checks in at least two places and log `push_allowed`...  Let the tool do it!

Thus, I vote for (1).

**Comment by rmarx** [comment]
Was removed and explanation text added.
