### ISSUE TITLE
data_moved describes three layers, but only two are specified

### ISSUE THREAD

**Issue by dtikhonov** [quiclog/internet-drafts#111]
> Used to indicate when data moves between the HTTP/3 and the transport layer (e.g., passing from H3 to QUIC stream buffers and vice versa) or between HTTP/3 and the actual user application on top (e.g., a browser engine). This helps make clear the flow of data, how long data remains in various buffers and the overheads introduced by HTTP/3's framing layer.

The paragraph above describes three layers: transport, HTTP/3, and user application.

The definition allows for only two layers:

```
    from?:"application"|"transport",
    to?:"application"|"transport",
```

In addition, the definition of "application" is ambiguous: it could be the application protocol (HTTP/3) or the user application.

**Comment by rmarx** [comment]
So, the current thinking is that this is always an HTTP level event, so there is no need to specify the "third" layer, as it is always HTTP. 
"application" in this case will always be the user application, not the application protocol (which, I agree, is not entirely clear or obvious).

Given this explanation, would you push for:
1. making this a more generic event by adding the "third layer" as well (not sure which category we would use for this event then though)
2. re-naming "application" to something else here to separate it from HTTP3/application protocol more clearly
3. keeping it as is but adding text to explain it more clearly

**Comment by dtikhonov** [comment]
I'd vote for (1), with the three layers being:
1. transport (or QUIC);
2. HTTP/3; and
3. application.

Note that the data may skip the HTTP/3 layer ([lsquic](https://github.com/litespeedtech/lsquic), for example, tries hard to avoid intermediate buffering) altogether, so the event should be able to describe that as well.

**Comment by rmarx** [comment]
Could you give an example of how data can skip the H3 layer in practice? I can understand this if you're for example using raw DATAGRAM frames in QUIC that don't use the HTTP/3 DATAGRAM stuff, but the moment you're carrying H3, you still need to strip out the frame headers in the H3 layer, no?

**Comment by dtikhonov** [comment]
Here is how reading from an HTTP/3 stream works in lsquic (in the best-case scenario):

1. The packet is decrypted and the decrypted payload is stored in a new memory object.  (This is data copy number 1.)
2. The packet is parsed.  This creates _STREAM_ frame marker objects.
3. If, as a result of a new marker, reading from a stream becomes possible, the user is notified via an "on stream write" event.  Note that *in the case of HTTP/3 stream, special magic happens internally*: the stream is fast-forwarded through the framing.  _DATA_ frames are processed and discarded.  You can peek at [how it's done in the `read_data_frames()` function](https://github.com/litespeedtech/lsquic/blob/v2.19.5/src/liblsquic/lsquic_stream.c#L1360L1363).
4. The user then reads data from stream using one of two ways.
   - **copy read**.  In this case, `lsquic_stream_read()` or `lsquic_stream_readv()` is called and data is copied into user-supplied buffer(s).  (This is data copy number 2.)
   - **zero copy**.  User can call `lsquic_stream_readf()` with a callback.  This callback will then be given a pointer to the data from the  first copy (in Step 1).  See [line 1367](https://github.com/litespeedtech/lsquic/blob/v2.19.5/src/liblsquic/lsquic_stream.c#L1367) -- this is where this callback is called.  Here, the user can copy the data or process it directly.

Note that there was no copy from transport layer into any intermediate layer.  So, no, stripping out frame headers does not mean that data must be copied.

**Comment by rmarx** [comment]
Is tied to #65
