### ISSUE TITLE
QPACK encoder and decoder each has its own state

### ISSUE THREAD

**Issue by dtikhonov** [quiclog/internet-drafts#112]
Each peer has two QPACK states: encoder and decoder.  `qpack`'s `state_updated` and `dynamic_table_updated` events do not make such differentiation, making the specification incomplete.  For example:

> This event is emitted when one or more entries are added or evicted from QPACK's dynamic table.

Which dynamic table is meant: encoder or decoder?

**Comment by rmarx** [comment]
Closed by adding an "owner" field to `dynamic_state_updated`.

Other qpack events either already had this field or are split out into created/parsed or encoded/decoded events, which makes this implicit.
