### ISSUE TITLE
Prepare for adoption

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#137]
List of thinks to keep in mind when preparing for QUIC wg adoption:
- Split QUIC and HTTP/3 event definitions into separate drafts (ensure proper cross-reference)
- Update editor names and affiliations
- Specify which value of `protocol_type` to use for each document (and change to array-based already?)
- Move shared stuff to the main schema document
  - RawInfo (though not 100% sure that's generic enough for all protocols?)
  - The whole "generic" category (error, warning, verbose, etc.)
  - Potentially the "Importance" indicators (Core, Base, Extra)
- Add more information about "previous versions" (e.g., two main versions in production, -01 and -02, those pre-date these adopted documents)
- Define a new version codepoint for the adopted drafts (now it's still draft-03-wip, but we also can't just do draft-00 or we'll overlap soon. Maybe qlog-0x?)
- rename master branch to main #140 
- Send e-mail to mailing list detailing the changes. Chairs will send a separate email with call for adoption afterwards.

Concrete steps for splitting / preparing the drafts according to @lpardue:

```
cp draft-marx-qlog-event-definitions-quic-h3.md draft-marx-qlog-quic-events.md
cp draft-marx-qlog-event-definitions-quic-h3.md draft-marx-qlog-h3-events.md

# add comment into draft-marx-qlog-event-definitions-quic-h3.md saying "beginning the split"

git add draft-marx-qlog-event-definitions-quic-h3.md draft-marx-qlog-quic-events.md draft-marx-qlog-h3-events.md

git commit -m "starting document split"

# then delete all the non-relevant text in draft-marx-qlog-quic-events.md and draft-marx-qlog-h3-events.md, and move necessary text to main-schema, then

git -rm draft-marx-qlog-event-definitions-quic-h3.md
git add draft-marx-qlog-quic-events.md draft-marx-qlog-h3-events.md

git commit -m "complete document split"

# then update editors and other metadata in the 3 documents

git commit -m "prepare for adoption"

# then submit 03, 00, 00 as individual I-Ds that we can issue a call for adoption on
```

**Comment by LPardue** [comment]
I hadn't appreciated you might need to also move stuff into the main schema. If that is too onerous a task at this stage then you could just mark it in the docs and leave it there for the being.

The important thing is the get the overall structure in place and agreed. The content of each document can then be evolved through the working group.
