### ISSUE TITLE
Better qpack support

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#20]
Some comments from @lpardue on qpack support:

> but how do you correlate a qpack header block event (or whatever you want to call it) to the header frame that it was carried in? maybe simply that header block event contains a stream_id for correlation

> other option is add raw_header_block to the HeaderFrame event data

Though that would still require additional events for encoder/decoder instructions, no?

> a qpack event that can consist of encoder instructions, decoder instructions and/or header block

So this seems the better option then, combined with the stream_id and expectation that the qpack events are logged in the same order as HeaderFrame's... (though not sure how important the ordering is personally).

Open questions:
- What about seeing what's in the dynamic table (or initial static table? or is that always the same?)? specific dynamic_table_updated event or... ?

**Comment by LPardue** [comment]
> What about seeing what's in the dynamic table (or initial static table? or is that always the same?)? specific dynamic_table_updated event or... ?

Some of this comes around to qlog design ethos - are you logging the message exchange objects or their effects or both (or some, depending on event types and deployment preference)?
