### ISSUE TITLE
Lacking a way to indicate ALPN list for client

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#28]
Currently, we can log a list of supported ALPN values for the server in "server_listening" and log the finally selected ALPN in "parameters_set". However, we lack a way to log the list of ALPN values the client supports (and offers the server).

Options:
- add `alpn_values?: Array<string> // ALPN values offered by the client / received by the server. Use parameters_set to log the actually selected alp` to "connection_started"
- make "alpn" in "parameters_set" an array instead of a string

I personally prefer the 1st option, since the second doesn't match the semantics of "set" (since it would be emitted twice) and logging the negotiation options should be optional in a "Base" (while the final value is in a "Core" event).

CC @jlaine

**Comment by huitema** [comment]
The first option is fine. It is nice to distinguish between proposal and results.
I could see for example:
...
"alpn_values": [ "h3-27", "hq-27", "h3-25", "hq-25" ],
```
And later:
...
"alpn": "h3-27",
```
But there a few issues. For example, what happens if the qlog entry contains both `alpn_values` and `alpn`?

**Comment by huitema** [comment]
I would prefer something like `proposed_alpn` instead of `alpn_values`, to emphasize that this is a proposal. This also has a nice way to solve the `proposed_alpn` vs `alpn` issues. For example, if a server logs:
```
"alpn_values": [ "h3-27", "hq-27", "h3-25", "hq-25" ],
"alpn": "h3-27",
```
That can be clear understood as "the client proposed these 4 values, and the server selected the 1sr one"

**Comment by jlaine** [comment]
I like the idea of strictly distinguishing offer values and the negotiated one. Alternative possible names (no string feelings about this):

```
"alpn_offer": ["a", "b", "c"]
"alpn_answer": "a"
```

**Comment by rmarx** [comment]
Added a separate `alpn_information` event for this. Not sure this is the best approach overall, but will see. Discussion on this continues in #85.
