### ISSUE TITLE
Require specific encoding for string fields

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#36]
For example, NewTokenFrame doesn't really need a length field if the encoding of the token is specified (e.g., if it is hex-encoded, byte-length is 2x token.length).

We already indicate hex-encoding at other places in the text (e.g., for version), maybe it's a good idea to enforce this across the board (then also specificy whether it should have 0x prefix or not etc. + examples).

Thanks to @marten-seemann for reporting

**Comment by marten-seemann** [comment]
This also applies to the NEW_CONNECTION_ID frame.

**Comment by marten-seemann** [comment]
Could this be as easy as saying that all byte-values are hex-encoding (omitting the 0x) somewhere in the introduction? Then this would apply to connection IDs, Retry tokens, NEW_TOKEN tokens, stateless reset tokens, etc.
