### ISSUE TITLE
Be more consistent in numbers vs strings for (potentially) large numbers (varints)

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#39]
Now, we only make varints strings if it's likely they will go over 2^53 (JSON's / JavaScript's number limit). 

For example, this means error codes are just numbers, even though they are varints, as it's unlikely to see a very large error code. However, for fields that are greased (e.g., see https://github.com/quicwg/base-drafts/pull/3360) they could be larger and a number no longer suffices.

See also dcil and scil in PacketHeader, which could be numbers but are now strings.

More in general: maybe it's best to simply allow both for all number fields and have the tools figure it out?

**Comment by huitema** [comment]
For me it would be very unnatural to treat Quic integers (varint encoded) as strings instead of numbers. Not impossible of course, one could always add quotes. But very unnatural.

**Comment by LPardue** [comment]
An approach some people are using for extension experimentation IS to pick large values for frame type, settings, stream types, etc.

**Comment by huitema** [comment]
@LPardue people do pick large numbers for experimentation, but the numbers are typically 2 bytes:
```
Frame types:
    ack_frequency = 0xAF,
    time_stamp = 757
TP:
    test_large_chello = 3127,
    enable_loss_bit_old = 0x1055,
    enable_loss_bit = 0x1057,
    min_ack_delay = 0xDE1A,
    enable_time_stamp = 0x7157
```
Even if we add another byte for versioning, traditional JSON will work just fine.

**Comment by rmarx** [comment]
The plan is to switch away from JSON/TypeScript notation in the draft and use explicit type annotations (e.g., uint32, uint64, etc.).

Then I'd add something stating that, if using a JSON format, you should decided yourself between a) encoding 64-bit values as strings or b) hope they won't be larger than 2^53 and log them as numbers. Tools would be strongly advised to support both string and number variants of these fields.

**Comment by LPardue** [comment]
and PRIORITY_UPDATE is using `0x1CCB8BBF1F0700` :)

It will be more difficult to make a general purpose library that can do what Robin suggests on the serialization side. It might also make it hard on the deserialization side in my specific implementation. 

That said, I really dislike the arbitrary schema inconstencies that exist today. So on balance I look forward to the proposed approach.

**Comment by rmarx** [comment]
If only we knew someone from the H3 Priorities team that could help mitigate that weirdly large Frame identifier...
