### ISSUE TITLE
Revisit the category for generic events

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#47]
We have a number of "generic" events in the draft (section 7, General error, warning and debugging definitions). These currently have their own categories: error, warning, info, debug, verbose, simulation. This is a bit awkward, since most of these only have a single event type. 

It might be a good idea to group these under a single category, e.g., "generic" or "general" or "textual" or... (or maybe 2: generic and simulation). Another option would be to define a new event field called `log_level` next to category (but that would increase overhead, as now we're essentially squatting on the category to provide that). 

The purpose of these events (sans simulation) is to allow one to replace the default textual logging with qlog completely (e.g., everything you now send to stdout/stderr with printf() would go into these kinds of events).

Thanks to @LPardue for reporting.

**Comment by kazu-yamamoto** [comment]
I would vote for "generic" or "general".
