### ISSUE TITLE
Logging of Retry and Version Negotiation packets

### ISSUE THREAD

**Issue by huitema** [quiclog/internet-drafts#62]
Initial, Handshake, 0-RTT and 1-RTT packets have a payload composed of a set of frames. Retry and Version Negotiation packets don't. The payload of retry packets is a retry token; the version negotiation packets contain a list of proposed versions. I wonder what the proper logging should be.

Staying close to the transport spec would get:
```
[118740, "TRANSPORT", "PACKET_RECEIVED", { 
    "packet_type": "version",
    "header": { 
        "packet_number": "0",
        "packet_size": 43,
        "payload_length": 20,
        "scid": "96f7ef87d6603a79",
        "dcid": "130b28a505315b13" },
    "proposed_versions": [ "ff00001b", "ff000019", "8aca3a8a" ]}]

[113660, "TRANSPORT", "PACKET_RECEIVED", {
    "packet_type": "retry",
    "header": {
        "packet_number": "0",
        "packet_size": 80,
        "payload_length": 32,
        "scid": "fa49f056d84c11c1",
        "dcid": "5bdfe3c33300b8b8" },
    "retry_token": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" }]
```
Does this look right?

**Comment by rmarx** [comment]
Was solved by including `supported_versions`, `retry_token`, `retry_token_length` and `stateless_reset_token` directly on `packet_sent` and `packet_received` (as this can conceptually be seen as being part of the "payload" of those special purpose packets, rather than their headers)
