### ISSUE TITLE
Properly specify stateless reset, retry and migration

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#64]
These concepts were in flux when -01 was made and are now much more settled.

Any thoughts on how to best approach this are more than welcome.

**Comment by rmarx** [comment]
For stateless reset, I can see two options:

1. make it a new PacketType and then simply use `packet_received` / `packet_sent`
2. make it a new event type with custom semantics

At least one implementer has indicated a preference for (1), since their stack only intends to support the core events.

**Comment by marten-seemann** [comment]
For stateless reset, both works for me. Most important thing is to get a way to log it at all, since this would be an interesting signal in production.
