### ISSUE TITLE
Add way to log contents of version negotiation packet

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#75]
Currently, there is no way to do this.

Possible approaches:
1. add `supported_versions:Array<string>` to `parameters_set` (similar to ALPN in #28)
2. add `supported_versions:Array<string>` to the `packet_*` events (similar to how we do stateless_reset

I personally have a preference for nr. 2, since it's consistent with how other packets are handled. ALPN is after all indeed a parameter, not a full packet. 

cc @mpiraux

**Comment by marten-seemann** [comment]
I'd argue that we need both. The supported versions is a parameter of the server that's interesting to know independent of if version negotiation was ever performed or not.

For the client, it's important to have a way to log the contents of a version negotiation packet, so adding it to the `packet_received` event makes sense.

**Comment by rmarx** [comment]
Related to #62

**Comment by rmarx** [comment]
Option 2 was introduced in commit ac00848b50c1da3feaf50f43938e962a091396b0.

However, we currently still lack a way to indicate which versions each endpoint supports by themselves (which is not always communicated over the wire).

**Comment by rmarx** [comment]
This was resolved for now by adding the new `version_information` event. Per #85, I'm not entirely sure that's the best approach here though. Closing this for now and keeping that issue open for general discussion. We can revisit this later depending on the outcome.
