### ISSUE TITLE
How to log transport parameters restored for 0-RTT

### ISSUE THREAD

**Issue by marten-seemann** [quiclog/internet-drafts#88]
When initiating a 0-RTT connection, the client restores transport parameters that it remembers from the last connection. Currently, it has to use the `parameters_set` event for this, with `owner` equal to `server`.

As I've already argued in #85, the `parameters_set` event would benefit from being split up. Taking this issue into consideration, maybe `parameters_sent`, `parameters_received` and `parameters_restored` would be a good fit?

**Comment by rmarx** [comment]
I have now added `transport:parameters_restored` and `http:parameters_restored` to help deal with this. I'm personally still not convinced this is better than simply logging them with "owner" equal to "server" as was the intent for draft-01, but do like the fact that it's more explicit this way. 

It will depend a bit on how we're going to end up doing `parameters_set` in general (see #85). If we keep that, maybe an "owner" value of "restored" would be an interesting middle ground. Closing for now though.
