### ISSUE TITLE
Make traditional JSON the default, provide two optimization options

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#89]
Currently, we utilize what I'd call a "csv" optimization, where the `time, category, event name and data fields` omit their keys (these are defined once in `event_fields`, much like csv columns are defined on top) and only log their values. This saves some bytes, but is non-trivial to parse (need to remember the order of the columns to know which value represents what) and to serialize (serializers typically don't like this type of thing).

This also breaks a bit with traditional JSON, which just lists the key names for every field as well. Using normal JSON would make it easier to serialize and parse, but increase the file size. 

There is a third optimized option, which is to replace all keys (and potentially also values) with indices into a lookup table/dictionary. This was discussed in #30 and, especially in combination with compression, seems like a good optimization option. 

So, to summarize, we have three options:
1. csv column optimization (current default and only supported)
2. pure JSON
3. dictionary optimization

The proposal is to switch qlog to nr 2 as default, and present nr 1 and 3 as optional optimizations (which can also be done post-hoc and offline). There would not be a given static dictionary (at least not in draft-02), with the dynamic dictionary always included in the qlog. Implementations are of course free to provide a built-in static dictionary themselves.

Tools would be required to only support nr 2, with optional support for 1 and 3. qvis would support all 3. 

Compression (gzip, brotli or other) would be also described but not mandated (qvis already supports gzip and brotli atm). 

cc @marten-seemann @LPardue

I also know @martinthomson had strong opinions on this, so it would be interesting to hear from you as I'd like to get this right for -02 now.

**Comment by marten-seemann** [comment]
I'd prefer to only have only 2. The choice of JSON as a logging format already means that we don't care about file size. I see little point in introducing piecemeal improvements to JSON's inefficiency to create what is essentially a new file format.

In addition to 2 I'd like to see a binary format (I know I've been nagging with this for a long time) that was built with efficiency considerations from the ground up.

**Comment by rmarx** [comment]
Moving to only/mainly 2 does make a binary format a lot easier I think, as things can be more directly mapped and interchanged (at least from what I know now of protobufs). 

One option would be to say: qlog draft is format agnostic (but uses JSON as examples because it's readable) and the events can be presented in other formats as well (i.e., qlog just defines the fields and their types per event, not their eventual "on the wire" serialization). Tools should provide conversions between other forms and JSON if they want to support alternate forms. Then, anyone can just make e.g., a protobuf format based on that. 

I am planning to move away from TypeScript format for the event definitions anyway, as it's needed to define e.g., the difference between 64-bit numbers, smaller numbers and strings (see #39). That requires a custom mapping to TypeScript/JSON anyway, so a protobuf (or similar) mapping fits in that logic too.

**Comment by LPardue** [comment]
I think there's a good chance I could switch to 2) without an API change. Addding an API method would allow user selection, and be non-breaking in the first case.

It seems nice if logs could self-identify the serialization format, otherwise you're relying on tools to do heuristics. This could be done with file extensions, or qlog parameters, or file magic. It's probably hard to get complete coverage but something might be a quick win.

**Comment by marten-seemann** [comment]
I was wondering if CBOR should be the standard format. The representation is very similar to JSON, but it provides better typing support:
1. it can unambiguously represent uint64s (so #39 would be solved)
2. it supports byte strings, eliminating the need for byte to string conversions (as remarked in #30). Those happen quite often, e.g. for connection IDs, retry token, stateless reset tokens etc.

There are also moderate file size savings, but those wouldn't be the main motivation here. CBOR of course doesn't provide any compression of map keys / values, so I'd expect CBOR qlogs to still be quite wasteful. Not sure if there's a schema-less serialization format that can use something like a dictionary to compress commonly used identifiers.

**Comment by rmarx** [comment]
Finished this transformation in f5db7cdc8cd0cf37bfe5f1b0b4c54fc56ffc5f28.

Draft 02 will use default JSON as prime format, with NDJSON for streaming. CBOR is discussed as an option, but provides few benefits over normal JSON when paired with compression. 

The text now also includes (limited) discussion and reasoning on the choice of JSON as the default format, per tests mainly discussed in #30.
