### ISSUE TITLE
Add mechanism for tracking coalesced packets

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#91]
Currently, this can be done implicitly by looking at `datagrams_sent` and `datagrams_received` events, but: a) these are very chatty if enabled for the entire connection and b) it's still implicit.

One proposed option (cc @marten-seemann) would be to add an optional `datagram_id` field to the `packet_*` and `datagrams_*` events that allows explicit correlation. This id would be an implementation-specific thing though, since QUIC itself does not define it (can be as easy as an implementation incrementing a counter).

Another point from Marten:
> Note that this would also allow to correlate packets that processed at different times: assume that one packet contained in a datagram can be processed immediately, but it is coalesced with a packet of an encyrption level that the endpoint doesn’t have keys for, and needs to buffer first

In that case, we probably also need to add the datagram_id to the `packet_buffered` event

**Comment by marten-seemann** [comment]
And to `packet_dropped`.
