### ISSUE TITLE
Add support for retry token and integrity tag

### ISSUE THREAD

**Issue by rmarx** [quiclog/internet-drafts#94]
Related to #86 , probably also best at home in the PacketHeader struct.

Proposal:
- use a single `token` field for both retry and initial tokens
- use a single `token_length` field for initial (explicit) and retry (implicit), `integrity_tag` field for retry

**Comment by marten-seemann** [comment]
I don’t think we need to log the integrity tag. We also don’t log the AEAD tag for normal packets.

**Comment by marten-seemann** [comment]
It would probably be interesting to log if the token is a Retry token or a NEW_TOKEN token.
For the client, this bit of information is trivially available, for the server it is after it unprotects the token (assuming unprotecting succeeds), as servers are required to be able to distinguish between Retry and NEW_TOKEN tokens.

**Comment by rmarx** [comment]
This was partially fixed in https://github.com/quiclog/internet-drafts/commit/ac00848b50c1da3feaf50f43938e962a091396b0. That was just the most straightforward change though, just adding fields that allow logging the tokens.

This does not yet allow differentiating NEW_TOKEN from Retry and we currently have no way of keeping those two separate (or e.g., to log that a NEW_TOKEN was successfully accepted). 

I am unsure about the design for that though... my gut tells me to move to separate `token_created` and `token_processed` events, which would in turn also allow logging the token's raw contents instead of logging them in the `packet_*` events. 

Example:
```
token_created
	type: "retry"|"resumption"|"stateless_reset",

       metadata:any, // to allow implementations to log which field are contained within an (encrypted) token
	
	raw_length?:uint32,
	raw?:bytes

token_processed
	type: "retry"|"resumption"|"stateless_reset",
	status: "accepted"|"rejected",
	
       metadata:any, // to allow implementations to log which field are contained within an (encrypted) token

	raw_length?:uint32,
	raw?:bytes

	trigger: why accepted/rejected 
		invalid_format
		invalid_source
		invalid_contents
		-> NOTE: for retry, this should also lead to a connection close with INVALID_TOKEN

```

However, I'm not sure this is the best approach. I'm going to mark this extension for draft-03 and keep the more straightforward option for draft-02.
