### ISSUE TITLE
remove the time_units configuration

### ISSUE THREAD

**Issue by marten-seemann** [quiclog/internet-drafts#95]
All time values are encoded as floats, so it doesn't make any difference if we encode them in ms or in μs.

Removing the configuration option makes it easier to implement qlog parsers, since there's less state to carry around to parse events.

**Comment by rmarx** [comment]
While I agree it makes it more difficult to parse, I'm not sure we can remove this?

Would you advocate for forcing implementation to log either ms or μs (and do x1000 or /1000 if they use the other internally) then? Currently, I think we have about 4 implementations doing μs.

**Comment by marten-seemann** [comment]
It doesn't matter which one is removed. Currently, I'm logging in ms (just because it's the default).
Changing this to μs would basically just being a change from calling `duration.Milliseconds()` to `duration.Microseconds()` (see https://github.com/lucas-clemente/quic-go/blob/master/qlog/event.go#L14). I assume it's the same for other implementations: You have one (language/implementaton-specific) time representation, and you convert that to whatever unit you export to qlog.
